### ISSUE TITLE
Monty Python Video Link Broken

### ISSUE THREAD

**Issue by gsfellis** [gsfellis/noob_snhubot#17]
The Monty Python video has been removed from YouTube.
Need to find a replacement and put it in cmds/airspeed_velocity.py

**Comment by gsfellis** [comment]
Link is not broken, but video does not play in Slack.

**Comment by jdthomason** [comment]
#21 Should fix this issue dandily.

**Comment by gsfellis** [comment]
Fixed in #21.  Great job @jdthomason ! 

Close #17

**Comment by gsfellis** [comment]
Fixed in #21.  Great job @jdthomason ! 

Close #17
