### ISSUE TITLE
Feature request: plugin architecture for adding COMMANDs

### ISSUE THREAD

**Issue by mattweidner** [gsfellis/noob_snhubot#6]
What would you think about implementing a simple architecture plugin for adding bot functionality? Perhaps something simple, along the lines of this? https://lkubuntu.wordpress.com/2012/10/02/writing-a-python-plugin-api/

This might make it a bit easier to add new functionality, in addition to enabling some automated checking to see if commands are being duplicated. Or, perhaps allowing multiple plugins to listen for the same command would be beneficial?

I'd love to hear your thoughts and I'd be happy to help work on implementing this. :-)

**Comment by gsfellis** [comment]
Yes! Love it.  I was trying to think of a better way to implement new commands.  Currently I'm using a poorly put together list.  It needs to be overhauled before implementing too many other commands.  I like this idea and I think it could be implemented for this, though I have only reviewed it a little bit.

Let me review this a little bit more in depth.  In the mean time, I'll give you collaborator so you can create a new branch and start playing.

**Comment by mattweidner** [comment]
Great! Thanks! I've never implemented a plugin architecture before and am excited to work on this. Let me know if your research gives you any other insights.
